site_name: keycloak-oauth-system
site_url: https://github.com/teward/KeycloakOAuth

theme:
  name: readthedocs
  color_mode: dark
  highlightjs: true
  hljs_languages:
    - yaml
    - python

plugins:
  - search    # Enables the built-in global search bar
  - mkdocstrings:    # Enables automatic API reference generation
      handlers:
        python:
          options:
            show_source: true  # Displays a collapsible source code block
            show_root_heading: true # Displays the title of the module/class

nav:
  - Home: index.md
  - API Reference: reference.md